<div style="<?= $msg ? 'display:block' : 'display:none' ?>">
<div class='alert alert-danger' role='alert'>  <?= $msg?></div>
</div>
<section class="background-radial-gradient overflow-hidden">
  <style>
    .background-radial-gradient {
      background: rgb(133, 133, 134);
      background: linear-gradient(90deg, rgba(133, 133, 134, 1) 0%, rgba(207, 206, 244, 1) 0%, rgba(210, 235, 255, 1) 100%);
    }

    #radius-shape-1 {
      height: 220px;
      width: 220px;
      top: -60px;
      left: -130px;
      background: radial-gradient(#44006b, #ad1fff);
      overflow: hidden;
    }

    #radius-shape-2 {
      border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;
      bottom: -60px;
      right: -110px;
      width: 300px;
      height: 300px;
      background: radial-gradient(#44006b, #ad1fff);
      overflow: hidden;
    }

    .bg-glass {
      background: rgb(54, 69, 80);
      backdrop-filter: saturate(200%) blur(25px);
    }

    .off {
      display: none;
    }

    .alert-secondary {
      background-color: red;
    }
  </style>
  <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
    <div class="row gx-lg-5 align-items-center mb-5">
      <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
        <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
          <img src="images/bluedit.png" width="500px" alt="">
        </h1>
        <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">

        </p>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
        <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
        <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
        <div class="card bg-glass">
          <div class="card-body px-4 py-5 px-md-5">
            <form method="post" enctype="multipart/form-data">
              <!-- 2 column grid layout with text inputs for the first and last names -->
              <div class="row">
                <div class="form-outline mb-4">
                  <div class="form-outline">
                    <input type="text" id="form3Example2" class="form-control" for="username" name="username" id="username" />
                    <label class="form-label">Username</label>
                  </div>
                </div>
              </div>
              <!-- Email input -->
              <div class="form-outline mb-4" action="index.php" method="post">
                <input type="email" id="form3Example3" class="form-control" for="email" name="email" id="email" />
                <label class="form-label">Email address</label>
              </div>
              <!-- Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="form3Example4" class="form-control" for="password" name="password" id="password" />
                <label class="form-label">Password</label>
              </div>
              <div class="form-outline mb-4">
                <input type="text" id="form3Example1" class="form-control" for="captcha" name="captcha" id="captcha" />
                <label class="form-label">Enter Captcha</label>
              </div>

              <div class="form-outline mb-4">
                <label>Captcha Code</label>
                <img src="captcha.php" alt="PHP Captcha">
              </div>
              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4">
                Sign up
              </button>
              <!-- Login button -->
              <p>You already have an account?<a href="login.php" class="link-info"> Login here </a></p>

          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>
<!-- Section: Design Block -->